"""Prompts for migrating a single-file mock into a framework stack."""

import json

from prompts.policies import FLUID_LAYOUT_POLICY

MIGRATION_SYSTEM_PROMPT = f"""You are a senior front-end engineer. You convert a single-file
HTML mock (React 18 UMD + Babel standalone + the Tailwind Play CDN) into the source
files of a Next.js App Router project written in TypeScript with Tailwind CSS v4.

Rules:
- Only write files whose paths match the allowed targets listed by the user. Paths
  are relative to the project root, use forward slashes, and never contain "..".
- The default export of src/app/page.tsx renders the mock's top-level App component.
- Put other components in src/components/<Name>.tsx, one default export each,
  imported as "@/components/<Name>".
- Add "use client" as the first line only in files that use hooks or event handlers.
- Replace React globals (React.useState, const {{ useState }} = React, ...) with named
  imports from "react". Drop ReactDOM.createRoot(...).render(...) and the root div.
- Keep every Tailwind class exactly as it is, except width caps that the layout
  rule below forbids. Drop the CDN <script> tags.
- Layout: {FLUID_LAYOUT_POLICY}
- Keep remote images as plain <img> elements (do not use next/image).
- Never use next/font. src/app/layout.tsx is regenerated by the tool with a local
  system font stack, so do not rely on anything you put there.
- Rewrite inline onclick strings and document.querySelector scripts as React state
  and handlers.
- Render must be deterministic and prerender-safe: `next build` prerenders every
  page, so never call new Date(), Date.now() or Math.random(), and never read
  window or document, while rendering (component bodies, JSX, useState/useMemo
  initialisers that also run on the server). Hard-code such values when they
  are static (e.g. write the copyright year as a literal instead of
  new Date().getFullYear()); otherwise start from a fixed initial state and
  compute them on the client in useEffect.
- The code must compile with `next build` (strict TypeScript): type props and
  event handlers.
- Do not call any tools.

Reply with only a JSON object of the form
{{"files": {{"<path>": "<file content>", ...}}}}
and nothing else."""


def migration_user_prompt(
    *, mock_html: str, app_title: str, migration_targets: list[str]
) -> str:
    targets = "\n".join(f"- {target}" for target in migration_targets)
    return f"""App title: {app_title}

Allowed target paths (glob patterns; "*" never crosses a "/"):
{targets}

Allowed extensions: .tsx, .ts, .css, .svg

Convert this mock:

<mock>
{mock_html}
</mock>"""


def repair_user_prompt(
    *, files: dict[str, str], build_log: str, migration_targets: list[str]
) -> str:
    """Ask for a fix after `next build` failed on the migrated files."""
    targets = "\n".join(f"- {target}" for target in migration_targets)
    file_map = json.dumps({"files": files}, indent=2, ensure_ascii=False)
    return f"""The Next.js production build failed with this log (last lines):

<build-log>
{build_log}
</build-log>

These are the files you produced for the app:

{file_map}

Fix the build. Change only what's needed to make `next build` succeed and keep
the rendered page the same. Return the corrected files as the same JSON file map
({{"files": {{"<path>": "<file content>"}}}}): include every file you changed;
files you leave out stay as they are.

Allowed target paths (glob patterns; "*" never crosses a "/"):
{targets}

Allowed extensions: .tsx, .ts, .css, .svg"""
